package it.polimi.ingsw.am46.server.model.cards.enums;

public enum EffectID {
    EFFECT1,
    EFFECT2,
    EFFECT3,
    EFFECT4,
    EFFECT5,
    EFFECT6,
    EFFECT7,
    EFFECT8,
    EFFECT9,
    EFFECT10,
    EFFECT11,
    EFFECT12,
    EFFECT13,
    EFFECT14,
    EFFECT15,
    EFFECT16,
    EFFECT17,
    EFFECT18,
    EFFECT19,
    EFFECT20,
    EFFECT21,
}
