package it.polimi.ingsw.am46.model.state;


import it.polimi.ingsw.am46.model.*;
import it.polimi.ingsw.am46.model.cards.characterCards.Artist;
import it.polimi.ingsw.am46.model.cards.characterCards.Hunter;
import it.polimi.ingsw.am46.model.cards.eventCards.CavePaintings;
import it.polimi.ingsw.am46.model.cards.eventCards.Hunt;
import it.polimi.ingsw.am46.model.cards.eventCards.Sustenance;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

public class ResolveEventStateTest {

    private Game game;
    private Board board;
    private Player p1;

    @BeforeEach
    void setupBaseGame() throws Exception {
        game = new Game();
        board = game.getBoard();

        p1 = new Player("Orazio");
        game.getPlayers().add(p1);
        game.setActivePlayer(p1);

        List<Space> spaces = new ArrayList<>();
        Space s1 = new Space(1, 0, 0);
        s1.setPlayer(p1);
        spaces.add(s1);

        TurnTile turnTile = new TurnTile(spaces);
        Field turnTileField = Board.class.getDeclaredField("turnTile");
        turnTileField.setAccessible(true);
        turnTileField.set(board, turnTile);

        game.setCurrentPhase(new ResolveEventState());
    }

    @Test
    void testEventOrdering_SustenanceResolvedLast() {
        System.out.println("=== TEST: MESOS RULE - SUSTENANCE RESOLVED LAST ===");

        p1.modifyFood(0);
        p1.modifyPP(0);
        p1.addCard(new Hunter(1, 1, 0, false, 2));

        // We add Sustenance FIRST in the bottom row, and Hunt SECOND.
        // 1) Sustenance: 1 mouth to feed, 0 food -> 0 Food, -2 PP penalty.
        // 2) Hunt: 1 hunter -> +1 Food, +2 PP. Final = 1 Food, 0 PP.

        //  according to Mesos rules, Sustenance must be sorted to the end!
        // 1) Hunt triggers first: +1 Food, +2 PP.
        // 2) Sustenance triggers last: 1 mouth to feed, Pays 1 Food -> Final = 0 Food, 2 PP.

        Sustenance sustenance = new Sustenance(100, 1, 0, false, 2); // 2 PP penalty
        Hunt hunt = new Hunt(101, 1, 0, false, 2); // 2 PP reward per hunter

        board.getBottomRow().add(sustenance);
        board.getBottomRow().add(hunt);

        game.getCurrentPhase().startPhase(game);

        // Assert that Sustenance was effectively resolved LAST
        assertEquals(0, p1.getFood(), "The food generated by the Hunt should have been consumed by the Sustenance!");
        assertEquals(2, p1.getPP(), "The player should not have taken starvation penalties because Sustenance happened last!");

        // Verify FSM Transition
        assertTrue(game.getCurrentPhase() instanceof PlaceTotemState, "After events, FSM should transition to EndRound then quickly to PlaceTotemState");
    }

    @Test
    void testStandardRoundIgnoresTopRowEvents() {
        System.out.println("=== TEST: STANDARD ROUND IGNORES TOP ROW EVENTS ===");

        p1.modifyFood(0);
        p1.modifyPP(0);
        p1.addCard(new Artist(2, 1, 0, 2));

        // Top Row: Cave Paintings (Requires 1 Artist, Reward: 3 PP)
        CavePaintings topEvent = new CavePaintings(102, 1, 0, false, 1, 2, 3);
        board.getTopRow().add(topEvent);

        // Act (Standard round 1)
        game.getCurrentPhase().startPhase(game);

        // Assert
        assertEquals(0, p1.getPP(), "Events in the Top Row MUST NOT be resolved during standard rounds!");
    }

    @Test
    void testEndGameResolvesAllEvents() throws Exception {
        System.out.println("=== TEST: MESOS RULE - FINAL ROUND RESOLVES ALL EVENTS ===");

        // Time travel to Round 10, Era 3
        Field roundField = Game.class.getDeclaredField("round");
        roundField.setAccessible(true);
        roundField.set(game, 10);

        Field eraField = Game.class.getDeclaredField("currentEra");
        eraField.setAccessible(true);
        eraField.set(game, 3);

        p1.modifyFood(0);
        p1.modifyPP(0);
        p1.addCard(new Artist(3, 1, 0, 2));
        p1.addCard(new Hunter(4, 1, 0, false, 2));

        // Top Row: Cave Paintings
        CavePaintings topEvent = new CavePaintings(103, 3, 0, true, 1, 2, 3); // Reward: 3 PP
        board.getTopRow().add(topEvent);

        // Bottom Row: Hunt
        Hunt bottomEvent = new Hunt(104, 3, 0, true, 2); // Reward: 1 Food, 2 PP
        board.getBottomRow().add(bottomEvent);

        game.getCurrentPhase().startPhase(game);

        // Assert that BOTH events were resolved successfully
        assertEquals(1, p1.getFood(), "Bottom row Hunt event should have been resolved!");
        assertEquals(5, p1.getPP(), "Both Hunt (2 PP) and Top Row Cave Paintings (3 PP) should have been resolved!");
    }

    @Test
    void testNoEventsTransition() {
        System.out.println("=== TEST: NO EVENTS SMOOTH TRANSITION ===");

        // Board is completely empty of Events (only normal Characters)
        board.getBottomRow().add(new Hunter(5, 1, 0, false, 2));

        // Act
        assertDoesNotThrow(() -> {
            game.getCurrentPhase().startPhase(game);
        }, "Phase should end smoothly and transition without exceptions if there are no events.");

        // Assert
        assertTrue(game.getCurrentPhase() instanceof PlaceTotemState, "Phase should end smoothly and start the next round at PlaceTotemState");
    }
}