package it.polimi.ingsw.am46.model.state;


import it.polimi.ingsw.am46.model.*;
import it.polimi.ingsw.am46.model.cards.characterCards.Artist;
import it.polimi.ingsw.am46.model.cards.characterCards.Hunter;
import it.polimi.ingsw.am46.model.cards.eventCards.CavePaintings;
import it.polimi.ingsw.am46.model.cards.eventCards.Hunt;
import it.polimi.ingsw.am46.model.cards.eventCards.Sustenance;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

public class ResolveEventStateTest {

    private Game game;
    private Board board;
    private Player p1;

    @BeforeEach
    void setupBaseGame() throws Exception {
        game = new Game();
        board = game.getBoard();

        p1 = new Player("Orazio");
        game.getPlayers().add(p1);
        game.setActivePlayer(p1);

        List<Space> spaces = new ArrayList<>();
        Space s1 = new Space(1, 0, 0);
        s1.setPlayer(p1);
        spaces.add(s1);

        TurnTile turnTile = new TurnTile(spaces);
        Field turnTileField = Board.class.getDeclaredField("turnTile");
        turnTileField.setAccessible(true);
        turnTileField.set(board, turnTile);

        game.setCurrentPhase(new ResolveEventState());
    }

    @Test
    void testEventOrdering_SustenanceResolvedLast() {
        System.out.println("=== TEST: MESOS RULE - SUSTENANCE RESOLVED LAST ===");

        p1.setFood(0);
        p1.addCard(new Hunter(1, 1, 0, false, 2));


        Sustenance sustenance = new Sustenance(100, 1, 0, false, 2); // 2 PP penalty
        Hunt hunt = new Hunt(101, 1, 0, false, 2); // 2 PP reward per hunter

        board.getBottomRow().add(sustenance);
        board.getBottomRow().add(hunt);

        game.getCurrentPhase().startPhase(game);

        // Assert that Sustenance was effectively resolved LAST
        assertEquals(0, p1.getFood(), "The food generated by the Hunt should have been consumed by the Sustenance!");
        assertEquals(2, p1.getPP(), "The player should not have taken starvation penalties because Sustenance happened last!");

    }

    @Test
    void testStandardRoundIgnoresTopRowEvents() {

        p1.setFood(0);
        p1.addCard(new Artist(2, 1, 0, 2));

        // Top Row: Cave Paintings (Requires 1 Artist, Reward: 3 PP)
        CavePaintings topEvent = new CavePaintings(102, 1, 0, false, 1, 2, 3);
        board.getTopRow().add(topEvent);

        // Act (Standard round 1)
        game.getCurrentPhase().startPhase(game);

        // Assert
        assertEquals(0, p1.getPP(), "Events in the Top Row MUST NOT be resolved during standard rounds!");
    }

    @Test
    void testEndGameResolvesAllEvents() throws Exception {

        // Time travel to Round 10, Era 3
        Field roundField = Game.class.getDeclaredField("round");
        roundField.setAccessible(true);
        roundField.set(game, 10);

        Field eraField = Game.class.getDeclaredField("currentEra");
        eraField.setAccessible(true);
        eraField.set(game, 3);


        p1.addCard(new Artist(3, 1, 0, 2));
        p1.addCard(new Hunter(4, 1, 0, false, 2));

        // Top Row: Cave Paintings
        CavePaintings topEvent = new CavePaintings(103, 3, 0, true, 1, 2, 3); // Reward: 3 PP
        board.getTopRow().add(topEvent);

        // Bottom Row: Hunt
        Hunt bottomEvent = new Hunt(104, 3, 0, true, 2); // Reward: 1 Food, 2 PP
        board.getBottomRow().add(bottomEvent);

        game.getCurrentPhase().startPhase(game);

        assertEquals(1, p1.getFood(), "Bottom row Hunt event should have been resolved");
        assertEquals(5, p1.getPP(), "Both Hunt (2 PP) and Top Row Cave Paintings (3 PP) should have been resolved");
    }

}