package it.polimi.ingsw.am46.server.db.dao;

import it.polimi.ingsw.am46.network.dto.LeaderboardEntry;
import it.polimi.ingsw.am46.server.db.DataBaseConnection;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * The type Game result da oimpl.
 */
public class GameResultDAOimpl implements GameResultDAO {

    @Override
    public void saveGameResults(int numPlayers, List<String> nicknames, List<Integer> scores,  List<Integer> positions) {
        // Step 1: Enter the match and retrieve the generated id
        int matchId = saveMatch(numPlayers);
        if (matchId == -1) {
            System.err.println("DB error: failed to save match, skipping results.");
            return;
        }
        // Step 2: Enter the results of all players in batch
        saveResults(matchId, nicknames, scores, positions);
    }

    private void saveResults(int matchId, List<String> nicknames, List<Integer> scores, List<Integer> positions) {
        String sql = "INSERT INTO MATCH_RESULTS (match_id, nickname, score, final_position) VALUES (?, ?, ?, ?)";
        try (Connection conn = DataBaseConnection.getConnection();
             PreparedStatement statement = conn.prepareStatement(sql)) {

            for (int i = 0; i < nicknames.size(); i++) {
                statement.setInt(1, matchId);
                statement.setString(2, nicknames.get(i));
                statement.setInt(3, scores.get(i));
                statement.setInt(4, positions.get(i));
                statement.addBatch(); //queue the query to execute
            }
            int[] results = statement.executeBatch(); //execute the query
            System.out.println("[DB] Rows inserted: " + results.length);

        } catch (SQLException e) {
            System.err.println("DB error saving results: " + e.getMessage());
        }
    }

    private int saveMatch(int numPlayers) {
        String sql = "INSERT INTO MATCHES (num_players) VALUES (?)";
        try (Connection conn = DataBaseConnection.getConnection();
             // Statement.RETURN_GENERATED_KEYS tells JDBC:
             // "after the insert, give me the autogenerated id from the AUTO_INCREMENT column"
             PreparedStatement statement = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            statement.setInt(1, numPlayers);
            statement.executeUpdate();

            // Get the id generated by the DB for this match
            ResultSet keys = statement.getGeneratedKeys();
            if (keys.next()) {
                int id =  keys.getInt(1);
                System.out.println("[DB] Match saved with id:" + id);
                return id;
            }


        } catch (SQLException e) {
            System.err.println("DB error saving match: " + e.getMessage());
        }
        return -1;
    }

    @Override
    public List<LeaderboardEntry> getLeaderboard(int numPlayers) {
        // NEW QUERY: Filter who finished 1st, group by name and count occurrences
        String sql = """
                SELECT mr.nickname, COUNT(mr.match_id) AS total_wins
                FROM MATCH_RESULTS mr
                JOIN MATCHES m ON mr.match_id = m.id
                WHERE m.num_players = ? AND mr.final_position = 1
                GROUP BY mr.nickname
                ORDER BY total_wins DESC
                """;

        List<LeaderboardEntry> leaderboard = new ArrayList<>();
        try (Connection conn = DataBaseConnection.getConnection();
             PreparedStatement statement = conn.prepareStatement(sql)) {

            statement.setInt(1, numPlayers);
            ResultSet rs = statement.executeQuery();

            while (rs.next()) {
                // BEWARE OF THE DTO: The match date no longer makes sense here,
                // because we are merging dozens of different matches into one line!
                // We use the 'score' field of your DTO to carry the number of wins.
                leaderboard.add(new LeaderboardEntry(
                        rs.getString("nickname"),
                        rs.getInt("total_wins")
                ));
            }
        } catch (SQLException e) {
            System.err.println("DB error getting leaderboard: " + e.getMessage());
        }
        return leaderboard;
    }

    @Override
    public int getPlayerPosition(String nickname, int numPlayers) {
        String sql = """
                WITH WinCounts AS (
                    SELECT mr.nickname, COUNT(mr.match_id) AS total_wins
                    FROM MATCH_RESULTS mr
                    JOIN MATCHES m ON mr.match_id = m.id
                    WHERE m.num_players = ? AND mr.final_position = 1
                    GROUP BY mr.nickname
                )
                SELECT COUNT(*) + 1 AS position
                FROM WinCounts
                WHERE total_wins > (
                    SELECT COUNT(mr2.match_id)
                    FROM MATCH_RESULTS mr2
                    JOIN MATCHES m2 ON mr2.match_id = m2.id
                    WHERE m2.num_players = ? AND mr2.final_position = 1 AND mr2.nickname = ?
                )
                """;

        try (Connection conn = DataBaseConnection.getConnection();
             PreparedStatement statement = conn.prepareStatement(sql)) {

            // Assignment of parameters for the three '?' present in the query
            statement.setInt(1, numPlayers);  // Parameter (WinCounts)
            statement.setInt(2, numPlayers);  // Parameter for the player-specific subquery
            statement.setString(3, nickname); // Parameter to identify the player in the subquery

            ResultSet rs = statement.executeQuery();
            if (rs.next()) return rs.getInt("position");

        } catch (SQLException e) {
            System.err.println("DB error getting position: " + e.getMessage());
        }
        return -1;
    }
}